[phases.setup]
nixPkgs = [
  'python312',
  'google-chrome',
  'glib',
  'nss',
  'atk',
  'cups',
  'libdrm',
  'mesa',
  'pango',
  'cairo',
  'xorg.libXcomposite',
  'xorg.libXdamage',
  'xorg.libXrandr',
  'libxkbcommon',
  'alsa-lib',
  'fontconfig',      # برای فونت‌ها
  'expat',           # برای XML parsing
  'xorg.libX11'      # پایه X11
]

[phases.build]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python main.py'
